[package]
name = "genorush"
version = "0.1.0"
edition = "2021"
authors = ["Qimeng Yang"]
description = "GenoRush: a fast, parallel, cross-platform CLI toolkit for genomics/transcriptomics data wrangling"
license = "MIT"

[[bin]]
name = "genorush"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
rayon = "1"
log = "0.4"
env_logger = "0.11"
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
